import fs = require('fs');
import { Observable } from 'rxjs';

const exec = require('child_process').exec;

const revision = new Observable<string>(s => {
  exec('git rev-parse --short HEAD',
    function (error: Error, stdout: Buffer, stderr: Buffer) {
        if (error !== null) {
          console.log('git error: ' + error + stderr);
        }
        s.next(stdout.toString().trim());
        s.complete();
    });
});

revision.subscribe((revisionValue) => {
  const content = '// this file is automatically generated by git.version.ts script\n' +
    `export const versions = {revision: '${revisionValue}'};`;
  fs.writeFileSync(
    'src/environments/versions.ts',
    content,
    {encoding: 'utf8'}
  );
});
